name: Continous Integration

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU (for multi-platform builds)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checking if Commit message contains "BUILD_CONTAINER_IMAGE"
      run: |
          if [[ $(git log -1 --pretty=%B) =~ "Build container" ]]; then
            echo "Commit message contains 'Build container', triggering container build."
            # Add steps for container building here
          else
            echo "Commit message does not contain 'Build container', skipping."
          fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:latest